const DB_NAME="FontStudioDB",STORE="projects",KEY="fontstudio:last";let currentProject=null;const BASE="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.,!?;:'"-+*/=()[]{}@#$%&";
function defaultProject(){let glyphs={};for(const c of BASE)glyphs[c]={advanceWidth:/[A-Z]/.test(c)?700:600,lsb:50,rsb:50,contours:[]};return{id:crypto.randomUUID(),name:"My Font",family:"My Font",style:"Regular",version:"1.0.0",author:"",copyright:"",unitsPerEm:1000,ascender:800,descender:-200,lineGap:200,weight:400,widthClass:5,updated:Date.now(),glyphs,kerning:{},guides:[{type:"h",value:0},{type:"h",value:800},{type:"h",value:-200}],layers:["Master"]}}
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:"id"})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putProject(p){p.updated=Date.now();let d=await openDB();return new Promise((res,rej)=>{let t=d.transaction(STORE,"readwrite").objectStore(STORE).put(p);t.onsuccess=()=>res();t.onerror=()=>rej(t.error)})}
async function getProject(id){if(!id)return null;let d=await openDB();return new Promise((res,rej)=>{let t=d.transaction(STORE,"readonly").objectStore(STORE).get(id);t.onsuccess=()=>res(t.result);t.onerror=()=>rej(t.error)})}
async function allProjects(){let d=await openDB();return new Promise((res,rej)=>{let t=d.transaction(STORE,"readonly").objectStore(STORE).getAll();t.onsuccess=()=>res(t.result.sort((a,b)=>b.updated-a.updated));t.onerror=()=>rej(t.error)})}
async function newFont(){let p=defaultProject();await putProject(p);localStorage.setItem(KEY,p.id);location.href="editor.html?id="+p.id}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function card(p){return `<article class="font-card" onclick="location.href='editor.html?id=${p.id}'"><div class="font-preview">Aa</div><div class="font-meta"><strong>${esc(p.name)}</strong><span>${esc(p.style)} · ${Object.keys(p.glyphs||{}).length} Glyphs · ${new Date(p.updated).toLocaleDateString("ja-JP")}</span></div></article>`}
async function renderLists(){let ps=await allProjects(),r=document.getElementById("recent"),f=document.getElementById("fonts");if(r)r.innerHTML=ps.slice(0,4).map(card).join("")||"<p>まだフォントがありません。</p>";if(f){let draw=()=>{let a=[...ps],q=(document.getElementById("search")?.value||"").toLowerCase();a=a.filter(p=>(p.name+" "+p.family).toLowerCase().includes(q));let s=document.getElementById("sort")?.value;if(s==="name")a.sort((x,y)=>x.name.localeCompare(y.name));if(s==="glyphs")a.sort((x,y)=>Object.keys(y.glyphs||{}).length-Object.keys(x.glyphs||{}).length);f.innerHTML=a.map(card).join("")||"<p>該当するフォントがありません。</p>"};draw();document.getElementById("search")?.addEventListener("input",draw);document.getElementById("sort")?.addEventListener("change",draw)}}
function download(name,data,type){let b=data instanceof Blob?data:new Blob([data],{type}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function getExportProject(){return currentProject||await getProject(new URLSearchParams(location.search).get("id")||localStorage.getItem(KEY))}
async function exportJSON(){let p=await getExportProject();download((p.name||"font")+".json",JSON.stringify(p,null,2),"application/json")}
function contourToSvg(c){if(!c?.length)return"";let s=`M ${c[0].x} ${1000-c[0].y}`;for(let i=1;i<c.length;i++)s+=` L ${c[i].x} ${1000-c[i].y}`;return s+" Z"}
async function exportSVG(){let p=await getExportProject(),c=Object.keys(p.glyphs)[0],g=p.glyphs[c];download(`${p.name}-${c}.svg`,`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1000"><path d="${(g.contours||[]).map(contourToSvg).join(" ")}"/></svg>`,"image/svg+xml")}
async function exportCSS(){let p=await getExportProject();download((p.name||"font")+".css",`@font-face{font-family:"${p.family}";src:url("${p.name}.woff2") format("woff2"),url("${p.name}.woff") format("woff"),url("${p.name}.ttf") format("truetype");font-weight:${p.weight};font-style:${p.style.toLowerCase()};}`,"text/css")}
document.getElementById("import")?.addEventListener("change",async e=>{let f=e.target.files[0];if(!f)return;let p=JSON.parse(await f.text());p.id=crypto.randomUUID();await putProject(p);location.href="editor.html?id="+p.id});
renderLists();