let history=[],future=[],zoomLevel=1,showGrid=true,showGuides=true,showRulers=true,showFill=true,showOutline=true,showHandles=false,currentGlyph="A",tool="select",drag=null,selected=[];
(async()=>{let id=new URLSearchParams(location.search).get("id")||localStorage.getItem(KEY);currentProject=await getProject(id);if(!currentProject){currentProject=defaultProject();await putProject(currentProject)}localStorage.setItem(KEY,currentProject.id);initEditor()})();
function initEditor(){document.getElementById("fontName").textContent=currentProject.name;document.getElementById("exportLink").href="export.html?id="+currentProject.id;populateGlyphs();loadGlyph();loadInfo();bindTabs();bindTools();setupCanvas();updatePreview();renderKerning();setInterval(()=>saveProject(true),15000)}
function glyphChars(){return Object.keys(currentProject.glyphs).sort((a,b)=>a.codePointAt(0)-b.codePointAt(0))}
function populateGlyphs(){let chars=glyphChars(),s=document.getElementById("glyphSelect"),grid=document.getElementById("glyphGrid"),q=(document.getElementById("glyphSearch")?.value||"").toLowerCase();s.innerHTML=chars.map(c=>`<option>${c}</option>`).join("");s.value=currentGlyph;grid.innerHTML=chars.filter(c=>c.toLowerCase().includes(q)||("u+"+c.codePointAt(0).toString(16)).includes(q)).map(c=>`<div class="glyph-cell ${c===currentGlyph?"selected":""}" onclick="selectGlyph('${c.replace(/'/g,"\'")}')"><b>${c}</b><span>U+${c.codePointAt(0).toString(16).toUpperCase().padStart(4,"0")}</span></div>`).join("");s.onchange=()=>selectGlyph(s.value)}
function selectGlyph(c){currentGlyph=c;selected=[];loadGlyph();populateGlyphs()}
function loadGlyph(){let g=currentProject.glyphs[currentGlyph];document.getElementById("glyphSelect").value=currentGlyph;document.getElementById("advance").value=g.advanceWidth;document.getElementById("lsb").value=g.lsb;document.getElementById("rsb").value=g.rsb;document.getElementById("metricGlyph").textContent=currentGlyph;document.getElementById("insGlyph").textContent=currentGlyph;document.getElementById("insUnicode").textContent="U+"+currentGlyph.codePointAt(0).toString(16).toUpperCase().padStart(4,"0");draw()}
function bindTabs(){document.querySelectorAll(".doc-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".doc-tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById("view-"+b.dataset.view).classList.add("active");if(b.dataset.view==="preview")updatePreview()})}
function bindTools(){document.querySelectorAll(".tool").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tool").forEach(x=>x.classList.remove("active"));b.classList.add("active");tool=b.dataset.tool})}
function setupCanvas(){let c=document.getElementById("glyphCanvas"),st=c.parentElement;let resize=()=>{c.width=st.clientWidth*devicePixelRatio;c.height=st.clientHeight*devicePixelRatio;draw()};new ResizeObserver(resize).observe(st);c.onpointerdown=down;c.onpointermove=move;c.onpointerup=()=>drag=null;resize()}
function point(e){let r=glyphCanvas.getBoundingClientRect();return{x:(e.clientX-r.left)/zoomLevel,y:(r.bottom-e.clientY)/zoomLevel}}
function down(e){let p=point(e);if(tool==="pen"){snapshot();let cs=currentProject.glyphs[currentGlyph].contours;if(!cs.length||!cs[cs.length-1]._open)cs.push(Object.assign([],{_open:true}));cs[cs.length-1].push({x:Math.round(p.x),y:Math.round(p.y),type:"line"});draw();return}if(tool==="rect"){snapshot();currentProject.glyphs[currentGlyph].contours.push([{x:p.x-100,y:p.y+150},{x:p.x+100,y:p.y+150},{x:p.x+100,y:p.y-150},{x:p.x-100,y:p.y-150}]);draw();return}if(tool==="ellipse"){snapshot();let a=[];for(let i=0;i<24;i++){let t=i*Math.PI*2/24;a.push({x:p.x+110*Math.cos(t),y:p.y+160*Math.sin(t),type:"curve"})}currentProject.glyphs[currentGlyph].contours.push(a);draw();return}let h=findNode(p);if(h){if(!e.shiftKey)selected=[];selected.push(h);drag={p,start:selected.map(x=>({...currentProject.glyphs[currentGlyph].contours[x.c][x.i]}))};updateSelectionInfo();draw()}else if(!e.shiftKey){selected=[];updateSelectionInfo();draw()}}
function move(e){let p=point(e);coords.textContent=`X: ${Math.round(p.x)}　Y: ${Math.round(p.y)}`;if(drag){let dx=p.x-drag.p.x,dy=p.y-drag.p.y;snapshot();selected.forEach((h,i)=>{let q=currentProject.glyphs[currentGlyph].contours[h.c][h.i],s=drag.start[i];q.x=s.x+dx;q.y=s.y+dy});drag=null;draw()}}
function findNode(p){let cs=currentProject.glyphs[currentGlyph].contours||[];for(let c=0;c<cs.length;c++)for(let i=0;i<cs[c].length;i++){let n=cs[c][i];if(Math.hypot(n.x-p.x,n.y-p.y)<14/zoomLevel)return{c,i}}return null}
function draw(){let c=document.getElementById("glyphCanvas");if(!c)return;let x=c.getContext("2d"),w=c.clientWidth,h=c.clientHeight;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);x.clearRect(0,0,w,h);x.fillStyle="#f7f9fc";x.fillRect(0,0,w,h);x.save();x.translate(w/2,h/2);x.scale(zoomLevel,-zoomLevel);x.translate(-500,-400);if(showGrid){x.strokeStyle="#e2e9f1";x.lineWidth=1/zoomLevel;for(let i=0;i<=1000;i+=50){x.beginPath();x.moveTo(i,-300);x.lineTo(i,1000);x.stroke();x.beginPath();x.moveTo(0,i);x.lineTo(1000,i);x.stroke()}}x.strokeStyle="#c8d5e2";x.beginPath();x.moveTo(0,0);x.lineTo(1000,0);x.stroke();let cs=currentProject.glyphs[currentGlyph].contours||[];for(let ci=0;ci<cs.length;ci++){let a=cs[ci];if(!a.length)continue;x.beginPath();x.moveTo(a[0].x,a[0].y);for(let i=1;i<a.length;i++)x.lineTo(a[i].x,a[i].y);if(!a._open)x.closePath();if(showFill){x.fillStyle="#9fc7e8aa";x.fill()}if(showOutline){x.strokeStyle="#4f7fa9";x.lineWidth=2/zoomLevel;x.stroke()}if(showHandles)for(let i=0;i<a.length;i++){x.beginPath();x.arc(a[i].x,a[i].y,5/zoomLevel,0,Math.PI*2);x.fillStyle=selected.some(s=>s.c===ci&&s.i===i)?"#755ab4":"#fff";x.fill();x.strokeStyle="#597da0";x.stroke()}}x.restore()}
function updateSelectionInfo(){selectionInfo.textContent=`${selected.length} nodes selected`}function snapshot(){history.push(JSON.stringify(currentProject));if(history.length>80)history.shift();future=[]}function undo(){if(history.length){future.push(JSON.stringify(currentProject));currentProject=JSON.parse(history.pop());populateGlyphs();loadGlyph();saveProject(true)}}function redo(){if(future.length){history.push(JSON.stringify(currentProject));currentProject=JSON.parse(future.pop());populateGlyphs();loadGlyph();saveProject(true)}}async function saveProject(silent=false){await putProject(currentProject);saveStatus.textContent=silent?"自動保存済み":"保存済み"}function zoom(d){zoomLevel=Math.max(.25,Math.min(4,zoomLevel+d*.25));zoomLabel.textContent=Math.round(zoomLevel*100)+"%";draw()}function toggleGrid(){showGrid=!showGrid;draw()}function toggleGuides(){showGuides=!showGuides;draw()}function toggleRulers(){showRulers=!showRulers;draw()}function toggleFill(){showFill=!showFill;draw()}function toggleOutline(){showOutline=!showOutline;draw()}function toggleHandles(){showHandles=!showHandles;draw()}function toggleFullscreen(){document.documentElement.requestFullscreen?.()}function prevGlyph(){let a=glyphChars(),i=a.indexOf(currentGlyph);selectGlyph(a[(i-1+a.length)%a.length])}function nextGlyph(){let a=glyphChars(),i=a.indexOf(currentGlyph);selectGlyph(a[(i+1)%a.length])}function copySelection(){localStorage.setItem("fontstudio:selection",JSON.stringify(selected.map(h=>currentProject.glyphs[currentGlyph].contours[h.c][h.i])))}function pasteSelection(){let a=JSON.parse(localStorage.getItem("fontstudio:selection")||"[]");if(!a.length)return;snapshot();currentProject.glyphs[currentGlyph].contours.push(a.map(p=>({...p,x:p.x+40,y:p.y+40})));draw()}function alignSelected(mode){if(!selected.length)return;snapshot();let p=selected.map(h=>currentProject.glyphs[currentGlyph].contours[h.c][h.i]),b=polygonBounds(p);p.forEach(q=>{if(mode==="left")q.x=b.x;if(mode==="right")q.x=b.x+b.w;if(mode==="center")q.x=b.x+b.w/2});draw()}function applyTransform(){if(!selected.length)return;let dx=Number(tx.value||0),dy=Number(ty.value||0),sx=Number(tw.value||1),sy=Number(th.value||1);snapshot();selected.forEach(h=>{let p=currentProject.glyphs[currentGlyph].contours[h.c][h.i];p.x=p.x*sx+dx;p.y=p.y*sy+dy});draw()}
function loadInfo(){let m={infoName:"name",infoFamily:"family",infoStyle:"style",infoVersion:"version",infoAuthor:"author",infoCopyright:"copyright",upm:"unitsPerEm",ascender:"ascender",descender:"descender",lineGap:"lineGap",weight:"weight",widthClass:"widthClass"};for(let [id,k] of Object.entries(m)){let e=document.getElementById(id);if(e){e.value=currentProject[k]??"";e.onchange=()=>{currentProject[k]=e.type==="number"?Number(e.value):e.value;document.getElementById("fontName").textContent=currentProject.name;saveProject()}}}}
["advance","lsb","rsb"].forEach(id=>document.getElementById(id).addEventListener("change",e=>{snapshot();currentProject.glyphs[currentGlyph][id==="advance"?"advanceWidth":id]=Number(e.target.value);saveProject()}));function updatePreview(){let e=document.getElementById("livePreview");if(e){e.textContent=document.getElementById("previewText").value;e.style.fontSize=document.getElementById("previewSize").value+"px"}}document.getElementById("previewText")?.addEventListener("input",updatePreview);document.getElementById("previewSize")?.addEventListener("input",updatePreview);
function renderKerning(){let b=document.getElementById("kerningList");if(!b)return;let a=Object.entries(currentProject.kerning||{});b.innerHTML=a.length?a.map(([k,v])=>{let[l,r]=k.split("|");return `<div class="kern-row"><b>${l}</b><b>${r}</b><span>Pair spacing</span><input type="number" value="${v}" onchange="currentProject.kerning['${k}']=Number(this.value);saveProject()"></div>`}).join(""):"<div style='padding:20px;color:#8a96a5'>カーニングペアはまだありません。</div>"}function addKerning(){let l=prompt("左の文字","A"),r=prompt("右の文字","V");if(!l||!r)return;currentProject.kerning[l+"|"+r]=-50;saveProject();renderKerning()}
window.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key==="s"){e.preventDefault();saveProject()}if((e.ctrlKey||e.metaKey)&&e.key==="z"){e.preventDefault();undo()}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key==="z"){e.preventDefault();redo()}if(e.key==="Delete"&&selected.length){snapshot();selected.sort((a,b)=>b.i-a.i).forEach(h=>currentProject.glyphs[currentGlyph].contours[h.c].splice(h.i,1));selected=[];draw()}});
let snapEnabled=true;
function toggleSnap(){snapEnabled=!snapEnabled; if(typeof saveProject==='function')saveProject(true)}
function snapValue(v){return snapEnabled?Math.round(v/10)*10:v}
