const DB_NAME="FontStudioDB", STORE="projects"; let currentProject=null;
function defaultProject(){return {id:crypto.randomUUID(),name:"My Font",family:"My Font",style:"Regular",version:"1.0.0",author:"",copyright:"",unitsPerEm:1000,ascender:800,descender:-200,updated:Date.now(),glyphs:{"A":{advanceWidth:700,lsb:50,rsb:50,contours:[]},"B":{advanceWidth:700,lsb:50,rsb:50,contours:[]},"a":{advanceWidth:560,lsb:40,rsb:40,contours:[]},"b":{advanceWidth:560,lsb:40,rsb:40,contours:[]}}};}
function db(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:"id"});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function allProjects(){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(STORE,"readonly").objectStore(STORE).getAll();t.onsuccess=()=>res(t.result.sort((a,b)=>b.updated-a.updated));t.onerror=()=>rej(t.error)})}
async function putProject(p){p.updated=Date.now();const d=await db();return new Promise((res,rej)=>{const t=d.transaction(STORE,"readwrite").objectStore(STORE).put(p);t.onsuccess=()=>res();t.onerror=()=>rej(t.error)})}
async function getProject(id){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(STORE,"readonly").objectStore(STORE).get(id);t.onsuccess=()=>res(t.result);t.onerror=()=>rej(t.error)})}
async function newFont(){const p=defaultProject();await putProject(p);location.href="editor.html?id="+p.id}
function card(p){return `<div class="font-card" onclick="location.href='editor.html?id=${p.id}'"><div class="font-preview">Aa</div><div class="font-meta"><strong>${esc(p.name)}</strong><span>${esc(p.style)} · ${Object.keys(p.glyphs||{}).length} glyphs</span></div></div>`}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
async function renderLists(){const ps=await allProjects();const r=document.getElementById("recent"),f=document.getElementById("fonts");if(r)r.innerHTML=ps.slice(0,4).map(card).join("")||"<p>まだフォントがありません。</p>";if(f){const draw=()=>{let a=[...ps],q=(document.getElementById("search")?.value||"").toLowerCase();a=a.filter(p=>p.name.toLowerCase().includes(q));if(document.getElementById("sort")?.value==="name")a.sort((x,y)=>x.name.localeCompare(y.name));f.innerHTML=a.map(card).join("")||"<p>該当するフォントがありません。</p>"};draw();document.getElementById("search")?.addEventListener("input",draw);document.getElementById("sort")?.addEventListener("change",draw)}}
function download(name,blob){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function exportJSON(){const p=currentProject||defaultProject();download((p.name||"font")+".json",new Blob([JSON.stringify(p,null,2)],{type:"application/json"}))}
async function exportCSS(){const p=currentProject||defaultProject();download((p.name||"font")+".css",new Blob([`@font-face{font-family:"${p.family}";src:url("${p.name}.woff2") format("woff2");}`],{type:"text/css"}))}
async function exportSVG(){const p=currentProject||defaultProject(),g=p.glyphs[Object.keys(p.glyphs)[0]]||{};download((p.name||"font")+"-"+Object.keys(p.glyphs)[0]+".svg",new Blob([`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1000"><path d="${(g.contours||[]).map(c=>c.path||"").join(" ")}"/></svg>`],{type:"image/svg+xml"}))}
document.getElementById("import")?.addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;const p=JSON.parse(await f.text());p.id=crypto.randomUUID();await putProject(p);location.href="editor.html?id="+p.id});
renderLists();