let history=[],future=[],zoomLevel=1,showGrid=true,currentGlyph="A"; 
(async()=>{const id=new URLSearchParams(location.search).get("id");currentProject=id?await getProject(id):defaultProject();if(!id)await putProject(currentProject);document.getElementById("fontName").textContent=currentProject.name;populate();draw();loadInfo();setupTabs();setupCanvas();})();
function populate(){const s=document.getElementById("glyphSelect");const grid=document.getElementById("glyphGrid");const chars=Array.from(new Set(Object.keys(currentProject.glyphs).concat([...`ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789`])));chars.forEach(c=>{if(!currentProject.glyphs[c])currentProject.glyphs[c]={advanceWidth:600,lsb:40,rsb:40,contours:[]};});s.innerHTML=chars.map(c=>`<option value="${c}">${c}</option>`).join("");grid.innerHTML=chars.map(c=>`<div class="glyph-cell" onclick="selectGlyph('${c}')"><strong>${c}</strong><span>U+${c.codePointAt(0).toString(16).toUpperCase().padStart(4,"0")}</span></div>`).join("");s.onchange=()=>selectGlyph(s.value)}
function selectGlyph(c){currentGlyph=c;document.getElementById("glyphSelect").value=c;const g=currentProject.glyphs[c];document.getElementById("advance").value=g.advanceWidth;document.getElementById("lsb").value=g.lsb;document.getElementById("rsb").value=g.rsb;draw()}
function setupTabs(){document.querySelectorAll(".side-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".side-tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById("panel-"+b.dataset.tab).classList.add("active");if(b.dataset.tab==="preview")updatePreview()})}
function setupCanvas(){const c=document.getElementById("glyphCanvas"),wrap=c.parentElement;const resize=()=>{c.width=wrap.clientWidth*devicePixelRatio;c.height=wrap.clientHeight*devicePixelRatio;draw()};new ResizeObserver(resize).observe(wrap);let down=false,lastX=0,lastY=0;c.onpointerdown=e=>{down=true;lastX=e.clientX;lastY=e.clientY};c.onpointerup=()=>down=false;c.onpointermove=e=>{const r=c.getBoundingClientRect();document.getElementById("coords").textContent=`X: ${Math.round((e.clientX-r.left)/zoomLevel)}　Y: ${Math.round((r.bottom-e.clientY)/zoomLevel)}`;if(down){lastX=e.clientX;lastY=e.clientY}};resize()}
function draw(){const c=document.getElementById("glyphCanvas");if(!c)return;const x=c.getContext("2d");x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);const w=c.clientWidth,h=c.clientHeight;x.clearRect(0,0,w,h);x.fillStyle="#f7f9fc";x.fillRect(0,0,w,h);if(showGrid){x.strokeStyle="#e7edf4";x.lineWidth=1;for(let i=0;i<w;i+=25)x.beginPath(),x.moveTo(i,0),x.lineTo(i,h),x.stroke();for(let i=0;i<h;i+=25)x.beginPath(),x.moveTo(0,i),x.lineTo(w,i),x.stroke()}x.strokeStyle="#c7d4e3";x.beginPath();x.moveTo(0,h/2);x.lineTo(w,h/2);x.stroke();x.fillStyle="#344052";x.font="360px Georgia";x.textAlign="center";x.textBaseline="middle";x.fillText(currentGlyph,w/2,h/2-20)}
function zoom(d){zoomLevel=Math.max(.25,Math.min(4,zoomLevel+d*.25));document.getElementById("zoomLabel").textContent=Math.round(zoomLevel*100)+"%";draw()}function toggleGrid(){showGrid=!showGrid;draw()}function toggleFullscreen(){document.documentElement.requestFullscreen?.()}
function snapshot(){history.push(JSON.stringify(currentProject));if(history.length>50)history.shift();future=[]}
function undo(){if(!history.length)return;future.push(JSON.stringify(currentProject));currentProject=JSON.parse(history.pop());populate();draw()}function redo(){if(!future.length)return;history.push(JSON.stringify(currentProject));currentProject=JSON.parse(future.pop());populate();draw()}
async function saveProject(){await putProject(currentProject);document.getElementById("saveStatus").textContent="保存済み"}
["advance","lsb","rsb"].forEach(id=>document.getElementById(id)?.addEventListener("change",e=>{snapshot();currentProject.glyphs[currentGlyph][id==="advance"?"advanceWidth":id]=Number(e.target.value);saveProject()}));
function loadInfo(){for(const [id,key] of Object.entries({infoName:"name",infoFamily:"family",infoStyle:"style",infoVersion:"version",infoAuthor:"author",infoCopyright:"copyright",upm:"unitsPerEm",ascender:"ascender",descender:"descender"})){const el=document.getElementById(id);if(el)el.value=currentProject[key]??"";el?.addEventListener("change",()=>{currentProject[key]=el.type==="number"?Number(el.value):el.value;document.getElementById("fontName").textContent=currentProject.name;saveProject()})}}
function updatePreview(){document.getElementById("livePreview").textContent=document.getElementById("previewText").value}document.getElementById("previewText")?.addEventListener("input",updatePreview);
window.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key==="s"){e.preventDefault();saveProject()}if((e.ctrlKey||e.metaKey)&&e.key==="z"){e.preventDefault();undo()}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key==="z"){e.preventDefault();redo()}});